#!/bin/bash

## Created By Aditya Shakya

#MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -14 -yoffset -00 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -0 -yoffset -1620 -width 10 -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Power")"
            case "$MENU" in
                *Lock) i3lock-fancy ;;
                *Logout) bspc quit 1 && pkill polybar;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
